apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Jvb3Q6cm9vdHBhc3N3b3JkQHBvc3RncmVzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3RyYW5zYWN0aW9ucz9zc2xtb2RlPWRpc2FibGU=  # Base64-encoded database connection string
