apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring 
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: metrics 
      protocol: TCP
      port: 9187
      targetPort: 9187
